### ISSUE TITLE
Introduce Void type, Remove IsArgTypeInconsequential

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1092]
Consider cases like If where true/false branch have incompatible types, such as returning 2 different records:
`If(test, Patch(Accounts,...), Patch(Contacts,...))`

This is not allowed in an expression, but very useful for behavior properties. 
Since there's a conflict , what's the return type for If here? 

Today, we have special casing to allow the mismatch in a behavior property, and look up the parents searching to see if the type is used.  And if not, we skip the type check.  This breaks the type system and is super hacky. For example, it means we can't assert that the value of a node matches the binder's computed type. This has led to crashes like #953, came up in #1032. Coverage gaps in #531. 

Instead, If() should just return Void in this case (where left & right can't match), and then we get a failure at the point that somebody tries to use void.  

We'll also need to be sure we still handle Blank and Error, and errors get propagated.

**Comment by gregli-msft** [comment]
Rather than a Void, should this return an untyped object instead?  It has a similar effect, the result can't be used directly and would be an error without an explicit cast, but it allows the maker to pull common fields with a type constructor and possibly the use of IsType/AsType on the result.  

In this example, `Text( If( true, First( Accounts ), First( Contacts ) ).Name )` would work if both schemas have a text Name property and `AsType( If( true, First(Accounts), First(Contacts), Accounts )` would return an Accounts record.  

The optimization to not do anything with the result can still be applied if it isn't used, but in a more generic way, and the type isn't driving it.

We also need to settle on our If type intersection/union semantics which may be related.
