### ISSUE TITLE
Cards Bugbash: Value layer still added for single valued collection variables

### ISSUE THREAD

**Issue by coletaylor1** [microsoft/Power-Fx#1674]
After creating a collection variable like this:

![image](https://github.com/microsoft/Power-Fx/assets/72627659/89038031-efd1-4bfb-9628-4972b9464135)

I would expect to be able to reference elements as primitive types directly. However, intellisense complains when setting a text label to `First(coll)` and also suggests the `Value` field.

![image](https://github.com/microsoft/Power-Fx/assets/72627659/85b215fb-99c5-48ac-bd0b-e4850a74d61d)

**Comment by coletaylor1** [comment]
Observe the same behavior using an expression with inline table declaration: `First([1,2,3])`

**Comment by MikeStall** [comment]
`[1,2,3]`  still creates a table with single column named "Value".

But since Fx doesn't have arrays, a pure scalar needs to be wrapped.
`[ 1,2,3]`
becomes:
`[{Value:1}, {Value:2},{Value:3}]`


The new behavior is to avoid an extra value where the element is a record, useful here:
`[  { X:1, Y:2}, {X:10, Y:20} ]`

**Comment by coletaylor1** [comment]
Makes sense. Agree behavior is by design
