### ISSUE TITLE
Using German number format in PowerApps is not possible on Android.

### ISSUE THREAD

**Issue by TobiasWegener** [microsoft/Power-Fx#1967]
# Bug: 
VirtualKeyboardMode.Numeric - Comma (",") is not available, only dot ("."), thus German format floats can not be entered in mobile application of PowerApps in German locations. 

# Pre-Condition:
TextInput with following conditions:

- TextFormat.Number
- VirtualKeyboardMode.Numeric
- Android Device (Android Version 12)
- All located in Germany 

## Steps to reproduce:
- Publish the app 
- Start the app in Edge-browser on an android device 
- Click on the TextInput to launch the virtual keyboard

## Post-Condition:
- Numeric keyboard displayed  
- Both dot and comma are visible
- Comma is grayed out
- Not able to type in coma as (float) separator (1,3 English equivalent would be 1.3)
- Dot can be selected, but TextInput deletes it immediately because the separator for numbers is a comma

## Comments
The standard local virtual keyboard on android should be used and should make it possible to enter floats in the local standard (either '.' or ',' as the separator in floats.).

**Comment by jorisdg** [comment]
Hi Tobias,

This looks like a bug or missing feature on the Power Apps device host or user interface controls. I will pass this information on to the appropriate folks but I suggest you file a support request to be able to follow-up with the product team as well.

This code repo and issues list (and the people maintaining it) deals specifically with the open source Power Fx language itself, independent of Power Apps, and there isn't much this team or this repo can help on your specific issue.

Again I will try and find the right folks and pass on this information, but I encourage you to go through support to track any progress, as I will close this issue here.

**Comment by MikeStall** [comment]
The community forums maybe a better place to file these:
https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
