### ISSUE TITLE
Ambiguous Blank() behaviour in MathTable functions

### ISSUE THREAD

**Issue by omprakaash** [microsoft/Power-Fx#328]
There seems to be ambiguity in the behavior of Blank() in numerical formulas involving tables( eg: AvgT.). 

For eg: ```Average([2, 2, Blank()], Value)```  yields 2 as expected. Here the Blank() value is ignored and is not equal to 0.

But,     ```Average([2, 2, Blank(), Value * Value)``` does not yield 4 but instead yields 2.6666665. Here the expression Blank() * Blank() when evaluated internally returns 0 and  count is incremented thus affecting the average.

One possible fix could be adding an additional check before running Eval on a row in RunAggregatorAsync() (Assuming tables are single-column)

``` C#
if (row.IsValue && row.Value.GetField(TableValue.ValueName) is not BlankValue) 
```
 

https://github.com/microsoft/Power-Fx/blob/c32eac0fe551381caf431ba4bfd3209a70d76ddb/src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs#L290-L306

**Comment by MikeStall** [comment]
This is a very interesting point. 
A related issue is using IsBlank() in the predicate, 
`CountIf([Blank(), 2,3], IsBlank(Value))` // returns 1

We should also double check with Excel's behavior.  
It is the current behavior in Power Apps, so changing it would be a breaking change and needs to be handled accordingly. 
Need to think about this...

**Comment by CarlosFigueiraMSFT** [comment]
That overload of the Average function will take the average of all non-blank values resulting from executing that expression... In the first case (`Average([2, 2, Blank()], Value)`) the results are 2, 2 and blank, so the third item is discarded and the result is 2... On the second case, however, the expression for the third item is not blank: _when passed to functions (or operators) that expect a numeric value, blanks are interpreted as 0_, which makes the value of `blank * blank` the same as `0 * 0` == 0. That's why the expression `Average([2, 2, Blank(), Value * Value)` will return 2.6666 (average of 4, 4 and 0).
