### ISSUE TITLE
EvalAsync() with invariant formulas

### ISSUE THREAD

**Issue by ahestin** [microsoft/Power-Fx#687]
```EvalAsync()``` method from ```RecalEngine``` class should be able to eval invariant formulas.

Repro step :
- Set **fr-FR** culture from ```PowerFxConfig``` of ```RecalcEngine```
- Write ```Concatenate("abc";"def")``` formula
- Store this formula into invariant format that corresponds to ```Concatenate("abc","def")``` (```,``` insteand of ```;```)
- ```EvalAsync()``` of the invariant formula gives the following error :  Errors: Error 17-18: Caractères inattendus. La formule contient « ParenClose » alors que « Error » est attendu.
Error 17-18: Caractères inattendus. Des caractères sont utilisés dans la formule de manière inattendue. 

I don't want to use two engines with different culture or set a culture before every evaluation.

Maybe you could add an invariant flag into the ```EvalAsync()``` method or add a new metohd ```EvalInvariantAsync()```.

**Comment by MikeStall** [comment]
This should be handled by a culture field on ParserOptions. Check, Eval already accept ParserOptions. 
However, the Culture settings is currently internal - it should probably be public so that it can be set. 

 " or set a culture before every evaluation." seems the same as "pass an invariant? flag to every evaluation"
We avoid introducing EvalInvariantAsync() because there are too many methods that accept parsing and would need to be updated.

**Comment by Felx-B** [comment]
Hi Mike, 
Thank you for the answer.
 We came to the same conclusion on the `ParserOptions` with @ahestin when we saw the internal `Culture` property

Would you accept a PR with the "internal to public" modification on this property ?
  We are kind of stuck, this prevent any usage with french profile.

Felix

**Comment by MikeStall** [comment]
@Felx-B - yes, we'd approve that!
Just make it public and add a unit test.

**Comment by MikeStall** [comment]
This is now available in nuget 
20220928-323377

from the daily builds.
