### ISSUE TITLE
Pi shows up in intellisense, but when selecting, is not Transformed to Pi(

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#840]
`Pi` shows up in intellisense, but when selecting the suggested `Pi` it doesn't auto complete to `Pi(` and stays as `Pi` which can be confusing to customers as they may misunderstand as some variable or enum etc... and complain it is not working.

**Comment by jas-valgotar** [comment]
It was decided to continue with the current behavior as it adheres to Monaco standards better.
------------------------------------------------------------------------------------------------------------------------------------
To me the ideal behavior is that BOTH:
•	(a) the paren is added automatically to match LFB behavior, AND 
•	(b) signature help should be automatically invoked through a natural flow (i.e, does not require the user to delete and retype a character).
I agree with Mike's principle that we need to be mindful of comparing UFB to existing (LFB) behavior - I think we've done a good job of that so far and will continue to do so.  We look at things like that on a case by case basis to make sure we're not re-implementing things from the LFB just for the sake of achieving parity and are instead focusing on the things that are valuable for the current milestone.  

That said, if there is a tradeoff to be made between the two given timelines and level of effort, I would suggest prioritizing (b) over (a) since I feel like signature help is more helpful to the user than an automatic paren.

-Chris Baldwin
