### ISSUE TITLE
Datetime tick precision

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#849]
Introduced by #728 and #782.
DateTime(Y,M,D,h,m,s,fff) ignores tick precision. This also might behave the same way for FormulaValue.New().

FormulaValue.New( WithoutSubMilliseconds( datetime ) )

**Comment by MikeStall** [comment]
The issue here is: Do DateTimeValues in the Power Fx language carry tick precision? 
The JS implementation does not, and the DateTime() function does not currently accept it. 

But C# DateTime does. 

This becomes an issue when serializing/deserializing a DateTime - if we do allow ticks, we don't want to lose them when round-tripping through a serializer.

**Comment by CarlosFigueiraMSFT** [comment]
I would posit that business applications would rarely (never?) need sub-millisecond precision. Is there any reason (besides "C# supports it") that we would need this kind of precision? If not, then the consistency across all platforms would probably make being a millisecond-precision language a better choice.
