### ISSUE TITLE
Specify expected type to Check/LSP

### ISSUE THREAD

**Issue by justinpark0916** [microsoft/Power-Fx#958]
If I have the formula that is used on a property that should only accept **text** values, but the formula has **Record** or **Table** values, it does not show any error indication. 

For example: `ForAll([1,2,3], ThisRecord.Value)` formula does not show error in FXEditor

![image](https://user-images.githubusercontent.com/104940715/210644713-9006a69b-2f1f-4927-8ef1-17ed0cb911a1.png)

**Comment by MikeStall** [comment]
PVA would also like this too. For example, when editing an expression in an Conditional node, they can ensure the type is boolean. 
Dataverse Formula Columns may also use this since editing an exisitng column can't change it's type. 

TBD what the design is here:
- how to specify the type to LSP 
- and specify to Check.

**Comment by MikeStall** [comment]
@nathansoz - this may also be useful to you.
