### ISSUE TITLE
Breaking error handling for custom function

### ISSUE THREAD

**Issue by susosuso** [microsoft/Power-Fx#999]
The new version of Power FX seems to wrap error value from custom functions to another error object -- 

https://github.com/microsoft/Power-Fx/commit/85a2baf0a4cf732da5a9d08d933c15c505b41808#diff-82a475d4e4e4571d947efb9787846da7381d8cbc1446ba284b94a02307b82384

https://github.com/microsoft/Power-Fx/blob/85a2baf0a4cf732da5a9d08d933c15c505b41808/src/libraries/Microsoft.PowerFx.Interpreter/ReflectionFunction.cs#L416-L421

This breaks our own custom error handling. Take the function below as example:

```csharp
internal class MyCustomFunction : ReflectionFunction
    {
        public MyCustomFunction () : base("MyCustom", FormulaType.Number, FormulaType.String)
        { }

        public static FormulaValue Execute(StringValue stringInput)
        {
            try
            {
                // do some other validation on stringInput (like Regex or other format validation).
            }
            catch
            {
                return FormulaValue.NewError(new ExpressionError { Kind = ErrorKind.InvalidArgument, Message = "Invalid string input..." });
            }

           ...
        }
    }
```

Before the NuGet update, our custom error would return to us.
`{ Kind = ErrorKind.InvalidArgument, Message = "Invalid string input..." `

After the NuGet update, the wrapper error is returned instead. 
`{ Kind = ErrorKind.Custom, Message = "Return type should have been n, found N" }`

Can we revert this behavior, or is there a recommended way for us to properly propagate our own error handling?

**Comment by jas-valgotar** [comment]
Hi @susosuso ,

Since now we are strictly checking the return type to be Identical to one provided to function (Which in NumberType here) you are seeing this error.

And it's good to see it did work as purposed and caught that Error was not created with proper type.

Can you try and add return type while creating the error to see if it resolves your issue?

I think changing Error to below would make it same as previous behavior.
`return FormulaValue.NewError(new ExpressionError { Kind = ErrorKind.InvalidArgument, Message = "Invalid string input..." }, FormulaType.Number);`

key part here is now we added the type for error! ;)

**Comment by susosuso** [comment]
Thank you @jas-valgotar for the explanation! The addition makes sense, and your suggestion fixed the errors 👍
